/* LISTS */
export const FETCH_LIST_METADATA = "FETCH_LIST_METADATA";
export const SET_LIST_METADATA = "SET_LIST_METADATA";
/* LIST ITEMS */
export const FETCH_ITEMS = "FETCH_ITEMS";
export const SET_ITEMS = "SET_ITEMS";