export const SET_SHORT_URL = "SET_SHORT_URL";
export const SET_LONG_URL_BY_INDEX = "SET_LONG_URL_BY_INDEX";
export const APPEND_LONG_URLS = "APPEND_LONG_URLS";
export const REMOVE_LONG_URL_BY_INDEX = "REMOVE_LONG_URL_BY_INDEX";
export const SHOW_SUBMIT_STATUS = "SHOW_SUBMIT_STATUS";
export const SAVE_URL_METADATA = "SAVE_URL_METADATA";
